### ISSUE TITLE
[2.0.0] xml errors in the log

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/ospd#169]
I often see this error message in the log:

> journal: OSPD - openvas: ERROR: (ospd.ospd) While handling client command:#012Traceback (most recent call last):#012  File "/usr/lib/python3.6/site-packages/ospd/ospd.py", line 762, in handle_client_stream#012    response = self.handle_command(data)#012  File "/usr/lib/python3.6/site-packages/ospd/ospd.py", line 1624, in handle_command#012    return self.handle_get_vts_command(tree)#012  File "/usr/lib/python3.6/site-packages/ospd/ospd.py", line 1011, in handle_get_vts_command#012    vts_xml = self.get_vts_xml(vt_id, filtered_vts)#012  File "/usr/lib/python3.6/site-packages/ospd/ospd.py", line 1545, in get_vts_xml#012    vts_xml.append(self.get_vt_xml(vt_id))#012  File "/usr/lib/python3.6/site-packages/ospd/ospd.py", line 1487, in get_vt_xml#012    vt_id, vt.get('affected')#012  File "/usr/lib/python3.6/site-packages/ospd_openvas/daemon.py", line 684, in get_affected_vt_as_xml_str#012    _affected.text = affected#012  File "src/lxml/etree.pyx", line 1018, in lxml.etree._Element.text.__set__#012  File "src/lxml/apihelpers.pxi", line 710, in lxml.etree._setNodeText#012  File "src/lxml/apihelpers.pxi", line 698, in lxml.etree._createTextNode#012  File "src/lxml/apihelpers.pxi", line 1493, in lxml.etree._utf8#012ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by cfi-gb** [comment]
Thanks for your report. This message was caused by a single VT added to the feed recently which had a special control char in the "affected" tag. This special char has already been removed and the updated VT should be included in one of the next feed updates, in addition the ospd-openvas is getting improved to handle such special chars more gracefully:

https://github.com/greenbone/ospd-openvas/pull/138

**Comment by jjnicola** [comment]
PR greenbone/ospd-openvas#139 fix this issue.
